### get list student

GET http://127.0.0.1:8080/student/get-list-student HTTP/1.1


#### get detail student
GET http://127.0.0.1:8080/student/get-student-detail/3 HTTP/1.1


#### create student
POST http://127.0.0.1:8080/student/create-student HTTP/1.1
Content-Type: application/json

{
    "hoTen": "Duong Xuan Quyet",
    "age": 18,
    "numberClass": 12
}

##### update sudents

PUT http://127.0.0.1:8080/student/update-student/3 HTTP/1.1
Content-Type: application/json

{
    "hoTen": "test jsdkfghks",
    "age": 20,
    "numberClass": 12
}

### delete student
DELETE http://127.0.0.1:8080/student/delete-student/5 HTTP/1.1